name: CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  workflow_dispatch:

jobs:
  ubuntu-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Formatting
        run: |
          python3 ./tests/formatting_check.py

      - name: Test run
        run: |
          pip install -r ./requirements.txt

          cd ./src
          python3 ./main.py --test
