# Tests the following:
# * Build API and Kernel
# * Install API and Kernel
# * Import API and Kernel (while doing docs)
# * Build docs
# * Formatting

name: Tests

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install sphinx sphinx-rtd-theme

      - name: Build and install wheels
        run: |
          make dist
          pip install build/dist/*.whl

      - name: Docs
        run: |
          cd ./docs
          mkdir ./_static ./_templates
          make html SPHINXOPTS="-W --keep-going"

      - name: Formatting
        run: python tests/formatting.py
