name: Tests

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  compile:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: C++
        run: |
          cd ./src/pvkernel; \
          make cpp;
      - name: Cuda
        run: |
          cd ./src/pvkernel; \
          make cuda;

  modules:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Kernel
        run: |
          cd ./src; \
          python3 -c "import pvkernel"
      - name: Pv
        run: |
          cd ./src; \
          python3 -c "import pv"

  formatting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run check
        run: python3 ./tests/formatting.py

  docs:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install packages
        run: pip install sphinx sphinx-rtd-theme
      - name: Build docs
        run: make docs
